#
###################################
# Site wide configuration
####################################
#
title: Rishav Jain 
email: jrishav05@gmail.com
description: Blog 
url: https://jrishav05.github.io


#
###################################
# Jekyll configuration
####################################
#
#timezone:          Asia/Kolkata
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title
future: true # To make posts with future dates visible 

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Rishav Jain 
  avatar: avatar.jpg
  job: "Mechanical Engineer at Mitsubishi Heavy Industries Compressor Corporation"
  bio: "Avid reader"
  email: jrishav05@gmail.com
  disqus-shortname: https-rishavblog-github-io 
  twitter: #username
  facebook: j.rishav #username
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: jrishav05 #username
  gitlab: #username
  stackoverflow: #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: rishav-jain-695622b6 #username
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
